package com.example.radical;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

public class HanziRadicalCollection {
    private final Map<Integer, List<Radical>> radicalsByStroke = new HashMap<>();
    private static final Map<String, ChineseCharacter> characterWholeMap = new HashMap<>();
    
    public static Map<String, ChineseCharacter> getCharacterMap() throws IOException {
        String filePath = "中文字库.txt"; // Adjust the path relative to the root of the JAR
        InputStream inputStream = ChineseCharacter.class.getClassLoader().getResourceAsStream(filePath);

        if (inputStream == null) {
            throw new IOException("File not found: " + filePath);
        }

        ObjectMapper objectMapper = new ObjectMapper();
        Map<String, ChineseCharacter> characterMap = objectMapper.readValue(inputStream, new TypeReference<Map<String, ChineseCharacter>>() {});

        inputStream.close();

        return characterMap;
    }
    
    public void addRadical(Radical radical) {
        radicalsByStroke.computeIfAbsent(radical.getStrokeCount(), k -> new ArrayList<>()).add(radical);
    }
    
    public void addListOfRadicalByStrokeNum(int strokeNumber, List<Radical> radicalList) {
    	radicalsByStroke.put(strokeNumber, radicalList); 
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("HanziRadicalCollection: \n");
        for (Map.Entry<Integer, List<Radical>> entry : radicalsByStroke.entrySet()) {
            sb.append("Stroke Number: ").append(entry.getKey()).append("\n");
            sb.append("Radicals: ").append(entry.getValue()).append("\n");
        }
        return sb.toString();
    }
    
    public static void main(String[] args) {
        try {
            Map<String, ChineseCharacter> characterMap = getCharacterMap();
            System.out.println(characterMap);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // methods generated by chatgpt 
//    public void addCharacterToRadical(String radicalName, int strokeCount, ChineseCharacter character) {
//        radicalsByStroke.getOrDefault(strokeCount, new ArrayList<>())
//                .stream()
//                .filter(radical -> radical.getName().equals(radicalName))
//                .findFirst()
//                .ifPresent(radical -> radical.addCharacter(strokeCount, character));
//    }
//
//    public List<String> getCharactersForRadical(String radicalName) {
//        List<String> characters = new ArrayList<>();
//        for (List<Radical> radicals : radicalsByStroke.values()) {
//            for (Radical radical : radicals) {
//                if (radical.getName().equals(radicalName)) {
//                    characters.addAll(radical.getCharacters());
//                }
//            }
//        }
//        return characters;
//    }

   }
